//! Foundational primitives shared across the kernel.
//!
//! No primitive in this module depends on any other kernel module.
//! These types are the building blocks every other module uses.
//!
//! - [`Global`] holds a single typed value with `OnceLock` semantics.
//! - [`KernelId`], [`WorkerId`], and [`SubsystemId`] are strongly-typed
//!   newtype identifiers, generated by [`IdGenerator`].
//! - [`Instant`], [`Deadline`], and [`Interval`] are kernel-owned time
//!   types. Other modules use these instead of touching `std::time`
//!   directly so the kernel can evolve its time model without leaking
//!   `std::time::Instant` into its public API.

pub mod global;
pub mod id;
pub mod time;

pub use global::Global;
pub use id::{IdGenerator, KernelId, SubsystemId, WorkerId};
pub use time::{Deadline, Instant, Interval};
